### PR TITLE
fix: tag-image parameter expansion using `circleci env subst`

### LINKED ISSUE #72: tag-image command doesn't expand envvars
## Orb version:

0.15

## What happened:

`steps:
    - gcp-gcr/tag-image:
          image: $CIRCLE_JOB
          source-tag: $CIRCLE_BRANCH
          target-tag: latest`

Resulted in `ERROR: (gcloud.container.images.add-tag) [gcr.io/**********/$CIRCLE_JOB:master] digest must be of the form "sha256:<digest>"`

## Expected behavior:

It should have expanded the `image` in the same way that `source-tag` was, but it did not

## Additional Information:

Probably the same fix that was done in #71 for build-and-push needs to be applied to `add-tag` as well

### PR DESCRIPTION
**Pull request by peterb-oanda**
Closes #72

### CODE REVIEW

File: src/scripts/tag-image.sh [hunk 1]
```diff
@@ -1,10 +1,12 @@
 #!/bin/bash
 
-SOURCE_TAG=$(eval echo "$ORB_EVAL_SOURCE_TAG")
-TARGET_TAG=$(eval echo "$ORB_EVAL_TARGET_TAG")
+ORB_VAL_REGISTRY_URL="$(circleci env subst "$ORB_VAL_REGISTRY_URL")"
+ORB_VAL_IMAGE="$(circleci env subst "$ORB_VAL_IMAGE")"
+
+SOURCE_TAG="$(circleci env subst "$ORB_EVAL_SOURCE_TAG")"
+TARGET_TAG="$(circleci env subst "$ORB_EVAL_TARGET_TAG")"
```
Comment (EricRibeiro) [inline src/scripts/tag-image.sh:7]: While this is the recommended way of doing parameter expansion, it is causing the tests to break due to a substring operation in the [tag parameter](https://github.com/CircleCI-Public/gcp-gcr-orb/blob/master/.circleci/test-deploy.yml#L27):

```yaml
tag: ${CIRCLE_SHA1:0:7}.$CIRCLE_BUILD_NUMBER
```

`eval echo` can handle that without a problem, but this is not something `envsubst` is capable of or should be capable of handling. Hence the error.

I gravitate towards leaving `eval echo` for now since removing it will result in a loss of functionality, therefore, a breaking change.

We plan on rewriting the GCP orbs in the near future. When we do so, we will likely move forward with `envsubst` as part of the several breaking changes.

Once you roll this back, the PR will be good to go!

File: src/scripts/tag-image.sh [hunk 2]
```diff
@@ -1,10 +1,12 @@
 #!/bin/bash
 
-SOURCE_TAG=$(eval echo "$ORB_EVAL_SOURCE_TAG")
-TARGET_TAG=$(eval echo "$ORB_EVAL_TARGET_TAG")
+ORB_VAL_REGISTRY_URL="$(circleci env subst "$ORB_VAL_REGISTRY_URL")"
+ORB_VAL_IMAGE="$(circleci env subst "$ORB_VAL_IMAGE")"
```
Comment (EricRibeiro) [inline src/scripts/tag-image.sh:4]: Perfect, thank you! 🙇

**Review by EricRibeiro — CHANGES_REQUESTED** [review]
I appreciate the help! 🙏

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/gcp-gcr?version=0.15.3
